name: "Auto Assign to Project"
on:
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  assign_one_project:
    name: "Assign to One Project"
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'issues' && github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'bug')
        uses: srggrs/assign-one-project-github-action@1.3.0
        with:
          column_name: "To do"
          project: "https://github.com/michael-barlow3/BaselineSampleVueJSWebPack/projects/1"
